version: "3"
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: foodmart
      MYSQL_USER: foodmart
      MYSQL_PASSWORD: foodmart
      MYSQL_ROOT_PASSWORD: foodmart
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: foodmart
      POSTGRES_PASSWORD: foodmart
      POSTGRES_DB: foodmart


